# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
- python>=3.4
- colorama
- cython
- h5py
- jupyter
- matplotlib
- numpy=1.13.*
- psutil
- scipy

- pip:
  - mpi4py
#  - pycuda
  - terminaltables
  - tqdm
